### ISSUE TITLE
UI Sections are at half height on Retina displays

### ISSUE THREAD

**Issue by squk** [ThePat02/BehaviourToolkit#22]
<img width="217" alt="image" src="https://github.com/ThePat02/BehaviourToolkit/assets/3443591/fd01d505-3620-4a3a-a9c3-3a678690e79a">

Similar to https://github.com/ThePat02/BehaviourToolkit/issues/4

**Comment by ThePat02** [comment]
@squk Can you look into the settings and look at your editor scaling?

It looks like the RichTextLabels somehow begin to scroll. Please take a look at this #23 and let me know if this fixes it!

**Comment by squk** [comment]
That fixes it!

**Comment by ThePat02** [comment]
Great! I will merge it into main and roll it out with the next patch. Meanwhile please use the cloned repo and not the asset lib version!
