### ISSUE TITLE
UX Enhancement: Use CTRL and SHIFT and ALT to alter node adding behaviour in the GUI Toolkit

### ISSUE THREAD

**Issue by SirPigeonz** [ThePat02/BehaviourToolkit#32]
I rly like GUI Toolkit for editing BT behaviours trees and I have idea how to improve it a bit.

Currently pressing Node buttons in Toolkit just adds the respective Node as a child of the selected Node in the Scene Tree.

My problem is this might be not exactly what I want and I have to re-organize Nodes by hand after, which is error prone and takes time.
Example, for Decorators I often woudl want to add them as a parent of the selected node. When adding BTLeaf to Composite nodes I would usually want to add them as next node in line.

I was thinking of extending the behaviour of the Toolkit UI when using keyboard modifiers like SHIFT, ALT and CTRL

Example:
CTRL + ALT + Click = Replace selected node with clicked node. (Double modifier for this one to be more safe from error.)
CTRL + Click = Swap selected node with clicked node in place and add selected node as clicked node child. (Nice for decorators and composites)
SHIFT + Click = Add clicked node as a next sibiling of the selected node. (Usefull for BTLeaf and FSMState so user desn't have to changle selection after editing current one)

To make this more disovarable and easy to remember we could add a strip with hints on the bottom of the Toolkit UI dock.

**Comment by SirPigeonz** [comment]
> Thank you for this suggestion. I will try some things out and adjust the UI accordingly. Maybe a general "?" button would be useful?

Yup that would work too, but maybe some icon or + sighn for it? '?' might look like it is "help" menu ^^

> Also I am not exactly sure if this does work with the Undo/Redo feature, but it totally should!

I have no idea :D

If you want to focus on other stuff for 2.0 then I can work on it and make a PR.

**Comment by ThePat02** [comment]
> If you want to focus on other stuff for 2.0 then I can work on it and make a PR. This is low priority enhancement tho, we can make it later.

Don't worry I got some time tonight and will make some changes to the UI. I'll @ you in the PR to check things.

**Comment by ThePat02** [comment]
@SirPigeonz You can check out the new PR! I need to rewrite the naming algorithm tho! Do you have any idea on how to communicate the shortcuts to the user?

**Comment by SirPigeonz** [comment]
> @SirPigeonz You can check out the new PR! I need to rewrite the naming algorithm tho! 

Uf I love it! Only thing that I would add is that if you replace/swap/append node the new node will be selected, so user will not loose input selection on the Scene Tree sub-window :) (and Tookit UI will not disapear that way)

Found also small bug. 
CTRL + M1 works correclty on the selected node but it's children are not moved with it :D

![image](https://github.com/ThePat02/BehaviourToolkit/assets/6152134/86ab1c97-f34e-46cc-94d2-da2471d800c6)

---

> Do you have any idea on how to communicate the shortcuts to the user?

I had idea to, add button to Tookit footer (ON by default) that will display extra bar on top of it that shows hints about modifiers (similar how modal tools in Blender do it) this way user will not have to remember them right away and he can disable them if he already memorized them.

Mockup:
![image](https://github.com/ThePat02/BehaviourToolkit/assets/6152134/0499e459-8c83-4958-9aea-4dcd902a4be2)

I also love what you did in the purple selection <3 :D

**Comment by SirPigeonz** [comment]
Instead for example `CTRL + M1 - Add as a parent` it could be `CTRL: Add as a parent` to be short?

**Comment by ThePat02** [comment]
> Uf I love it! Only thing that I would add is that if you replace/swap/append node the new node will be selected, so user will not loose input selection on the Scene Tree sub-window :) (and Tookit UI will not disapear that way)

I already got this on my TO-DO list!

> CTRL + M1 works correclty on the selected node but it's children are not moved with it :D

Already noticed this too! Thanks for testing tho!

> Instead for example CTRL + M1 - Add as a parent it could be CTRL: Add as a parent to be short?

Yes, I think using `M1` would be more confusing!

**Comment by ThePat02** [comment]
Added a new help label + button.
Fixed reparenting.
Fixed selection.

**Comment by ThePat02** [comment]
> I also love what you did in the purple selection <3 :D

Thank you haha. I thought the plugin was in tire need of some default uitlity leaves.

**Comment by ThePat02** [comment]
Okay, I just pushed the last fixes. Please try it out if it works for you and I can release the changes to the asset lib!

**Comment by SirPigeonz** [comment]
Tested and works great so far! :) Only thing that is missing is docs for new nodes.
I also created a PR with Leaf that can emit a `signal` check it out before you will make the release.

**Comment by ThePat02** [comment]
Docs are on hold, since I want to rewrite them later down the line. I think the new leaves are very simple and easy to understand. I made sure they have proper in-engine documentation.
