### ISSUE TITLE
Change Spaces indentation to Tabs

### ISSUE THREAD

**Issue by SirPigeonz** [ThePat02/BehaviourToolkit#36]
When I open BT scripts they often are corrected by Godot and indentations are auto corrected from spaces to tabs. ^^'

I think we should stick to official conventions and use tabs for GDScript so there will be less issues and hassle with that.

Or maybe you use external editor and it had configured indents as spaces by default?

**Comment by ThePat02** [comment]
> Or maybe you use external editor and it had configured indents as spaces by default?

Yes, I indeed use Visual Studio Code, because I think it is WAY better than the embedded editor.  My university has us use spaces instead of tabs

But you are right! When I update the whole code for 2.0.0 I will replace all tabs with spaces. Luckily there is a shortcut for that

**Comment by SirPigeonz** [comment]
> > Or maybe you use external editor and it had configured indents as spaces by default?
> 
> Yes, I indeed use Visual Studio Code, because I think it is WAY better than the embedded editor. My university has us use spaces instead of tabs

Yup I use VSCode for Python and use 4 spaces there like PEP8 is demanding :) Probably thats why they demanded of you to use 4spaces it's a convention in Python :)

> But you are right! When I update the whole code for 2.0.0 I will replace all tabs with spaces. Luckily there is a shortcut for that

Awesome!

**Comment by SirPigeonz** [comment]
Oh, a tip, you can configure VSC to use tabs for .gd files I just don't remember how not a VSC power user yet xD and I use Godot for GDS so never checked how to do that...

**Comment by ThePat02** [comment]
I think it is actually set to this by default, but at some point I was writing some code on a Codespace and pasted it in. I think that's when I converted most of the tabs to spaces lol

**Comment by ThePat02** [comment]
We are going to use `gdformat` from https://github.com/Scony/godot-gdscript-toolkit whenever 2.0 is ready.

**Comment by ThePat02** [comment]
New GitHub action for automatically formatting this repo has been added!

**Comment by SirPigeonz** [comment]
> New GitHub action for automatically formatting this repo has been added!

I've seen you had to revert it's effects.
It did the opposite and switched tabs to spaces xD
Also, it broke `enum`s because they didn't have `,` on the last `enum`. I think it will treat them as vertical `enum`s if they will have one...

I haven't looked into this tool yet so I don't know how to change the indentation situation :/

**Comment by ThePat02** [comment]
> I've seen you had to revert it's effects.

That was just to test things out.

> It did the opposite and switched tabs to spaces xD

I don't think it did? Looks fine to me!

> Also, it broke enums because they didn't have , on the last enum. I think it will treat them as vertical enums if they will have one...

Good point, I was looking for a fix!

**Comment by SirPigeonz** [comment]
> > It did the opposite and switched tabs to spaces xD
> 
> I don't think it did? Looks fine to me!

Oh, you are right! It switched spaces to tabs correctly. I must have checked on revert commit... xD

> Good point, I was looking for a fix!

No prob :)

It is explained here, that it needs trailing comma on last element (comment on the end of the array):
https://github.com/Scony/godot-gdscript-toolkit#formatting-with-gdformat-more

**Comment by ThePat02** [comment]
> trailing commas are often good practice in longer lists because it's harder to forget one when you extend them xD

Yeah, my uni doesnt want them tho

Already fixed it for the 2.0 branch
