### ISSUE TITLE
Godot 4.2 what is the policy

### ISSUE THREAD

**Issue by SirPigeonz** [ThePat02/BehaviourToolkit#49]
Ok so we have new Godot, what now?

Are we migrating on it with 2.0, if yes when (after waht PRs will be merged).

And do we make special version of 1.x branch for 4.2?

**Comment by ThePat02** [comment]
I already updated 2.0.0. Everything works just out of the box without any changes. I see no reason why we shouldn't use 4.2 going forward.

**Comment by SirPigeonz** [comment]
Awesome, so I switched to 4.2 for BT dev too.
