### ISSUE TITLE
Tween node - add option to use value from blackboard

### ISSUE THREAD

**Issue by evilenzo** [ThePat02/BehaviourToolkit#50]
It would be a great feature to use value from blackboard cause it's not cool to have hardcoded value or set value from other leaves/scripts

**Comment by ThePat02** [comment]
Do you mean you want to tween a value from the blackboard?

**Comment by ThePat02** [comment]
> It would be a great feature to use value from blackboard cause it's not cool to have hardcoded value or set value from other leaves/scripts

Oh I see what you mean. I think one method to solve this is to add another `tween_value_type` called "Custom Script", so you can implement your own logic! I will see what I can come up with :$

**Comment by ThePat02** [comment]
Would you mind checking out #51 and tell me if this works for you?

**Comment by evilenzo** [comment]
> Would you mind checking out #51 and tell me if this works for you?

Sorry for late reply. I think that should do the job!
