### ISSUE TITLE
Loop decorator leaf

### ISSUE THREAD

**Issue by evilenzo** [ThePat02/BehaviourToolkit#53]
Title speaks for itself. It's kinda hard to make loops rn. I know that classic BT doesn't have this but such feature seems reasonable

**Comment by ThePat02** [comment]
Well there is the "Repeater" decorator. What kind of functionality are you missing exactly?

**Comment by evilenzo** [comment]
Conditions would be great. I think it should have opportunity to use custom script

**Comment by evilenzo** [comment]
Also as I can see it applies only for one leaf and what if I want to repeat some leaves sequence?

**Comment by ThePat02** [comment]
> Conditions would be great. I think it should have opportunity to use custom script

I will look into it.

I think you could use sequences to have more leaves looping.

**Comment by evilenzo** [comment]
I think I understood your idea so the issue can be closed

**Comment by evilenzo** [comment]
This is my fault I don't understand flow correctly. I just had signaling exit node in the end of sequence so sequence worked exactly one time. Without it sequence will loop like I expect

**Comment by evilenzo** [comment]
But wait. What if I want a sequence that executes every leaf exactly once with such logic:
1. Fail if any of leaves fail
2. Succes if ALL of leaves success
3. Go to next leaf if it is RUNNING

**Comment by evilenzo** [comment]
Oh well, I checked sequence logic but let me check again...

**Comment by evilenzo** [comment]
It seems like SimpleParallel does what I want but the naming can be misleading. It is not actually parallel

**Comment by ThePat02** [comment]
> But wait. What if I want a sequence that executes every leaf exactly once with such logic:
> 
> 1. Fail if any of leaves fail
> 2. Succes if ALL of leaves success
> 3. Go to next leaf if it is RUNNING

Oh yes, `Simple Parallel` is exactly what you want. The naming can be somewhat misleading, indeed! The node is somewhat unstable #38 and I am not sure if all policies work correctly right now. If you encounter any problems, make sure to report the bug on #38 and/or dive in the code and try to fix it yourself. Didn't have time to implement proper unit testing.

**Comment by evilenzo** [comment]
Everything works ok but we probably should rename it to something more clear

**Comment by evilenzo** [comment]
Because it looks like it is more a loop node instead of parallel

**Comment by ThePat02** [comment]
> Everything works ok but we probably should rename it to something more clear

I didn't come up with this name! It is a standardized name for this type of composite (as seen in [Unreal Engine](https://docs.unrealengine.com/4.27/en-US/InteractiveExperiences/ArtificialIntelligence/BehaviorTrees/BehaviorTreeNodeReference/BehaviorTreeNodeReferenceComposites/) for example) and if you think about it, all leaves are executed "side by side" before this node returns a value. A Sequence performs them after each other. (Well a Parallel technically does that too, but you get the concept)
