### ISSUE TITLE
Maybe include behaviour and behavior in the title of your plugin in godot

### ISSUE THREAD

**Issue by Emma-Black** [ThePat02/BehaviourToolkit#59]
Just so its easier to find for those of us who are extremely good at things like freedom and eagles 🦅 but have for some reason decided to drop the letter `u` from a bunch of words!

**Comment by Emma-Black** [comment]
(sorry its not really an issue, just realized why it was hard for me to find it in the godot asset tab)

**Comment by ThePat02** [comment]
This is a valid point! I just picked the word I learned at school without giving it too much thought. It's a thought choice and Godot doesn't allow tags on the Asset Lib yet. Having both in the title seems kind of confusing and overkill too...

**Comment by Emma-Black** [comment]
Very true! I had seen someone link this project a while back and made a mental note to myself to check it out, but then when I popped into the asset tab it didn't come up, then I went back and found the link and realized why It didnt come up!

Yeah I guess its a shame you cant really have tags or a searchable body of text other than the name
