### ISSUE TITLE
Convert BehaviourToolKit to use resources and graphic edit

### ISSUE THREAD

**Issue by Shadowblitz16** [ThePat02/BehaviourToolkit#65]
Consider converting behavior toolkit to use graph edit and resources..

Here are the pros of doing so...
- Behaviours could still be saved and files
- Behaviours would be resource based so they would be faster
- Behaviours would be resource based so no more accidentally overriding _physics process. everything is done through your own bt interface.
- Behaviours would be safer to export as moddable content since users would only have access to what is provided instead of a whole scripting language
- Fsm events could be predefined and chosen with a dropdown box (no more invalid events)
- Parent a child relationships could be staticly typed. (no more adding a Transition node as a child to another transition node only State nodes)
- Actor signals and properties could be type checked.
- AnimationTree could possibility be used as the node. aka behaviour toolkit root could extended AnimationTreeRoot

Here are the cons...
- Rewriting everything as a resource and graph edit takes time
- Might require implementation of some stuff for getting things like input or using physics since there would be no _input or _physics_process methods
- Behaviors and states that are saved might need to be populated into a registry of some sort so we can create them later in the graph edit.

**Comment by ThePat02** [comment]
In short: There are way to many benefits of just keeping them as nodes. They are easier to edit, extend and use. You are however free to make your own fork and implement these things by yourself, but the plugin is heading in another direction, as one of the next big PRs will allow users to dynamically move nodes around at runtime. #47 

> Parent a child relationships could be staticly typed. (no more adding a Transition node as a child to another transition node only State nodes)

When are you doing this? Transition Nodes should only be children of State nodes.

> Actor signals and properties could be type checked.

This can be done now by using something like `actor = actor as CharacterBody2D`.

> AnimationTree could possibility be used as the node. aka behaviour toolkit root could extended AnimationTreeRoot

No, this is not possible. You would have to build your own Control.
