### ISSUE TITLE
LeafCondition for Vector2.length?

### ISSUE THREAD

**Issue by Shadowblitz16** [ThePat02/BehaviourToolkit#66]
How do I use the LeafCondition for Vector2.length?
![image](https://github.com/ThePat02/BehaviourToolkit/assets/2453707/d45e7b94-1582-4215-888a-1a776e0eed78)

**Comment by ThePat02** [comment]
I just added scriptable conditions for you to try out in #63. Just use the latest `main` commit and they will be there.

**Comment by ThePat02** [comment]
Oh, and `condition_property` is a `StringName` and only accepts properties that will then use `actor.get(condition_property)` to fetch the value. Thus, no functions or code of any kind is valid there.
